import type { Metadata } from "next";

import "./globals.css";

import { Navbar } from "@/src/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-midnight text-foam">
        <main className="flex min-h-[100dvh] mx-auto w-screen flex-col items-center gap-24 overflow-x-hidden md:gap-48 px-4 md:px-0">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
